[general]
default-save-path=~/mail-attachments
pgp-provider=gpg
unsafe-accounts-conf=true

[ui]
index-columns=flags:4,name<25%,subject,date>=
timestamp-format=2006-01-02
this-day-time-format=15:04
this-week-time-format=Mon 15:04
this-year-time-format=Jan 02

[statusline]

[viewer]
alternatives=text/plain,text/html

[compose]

[multipart-converters]

[filters]
text/plain=colorize
text/calendar=calendar
#text/html = html | colorize
text/html  = ! w3m -I UTF-8 -T text/html | colorize
message/delivery-status=colorize
message/rfc822=colorize
.headers=colorize

[openers]

[hooks]

[templates]
