#!/bin/bash

filenames=("bashrc" "vimrc" "tmux.conf" "inputrc" "obsidian.vimrc")

link() {
  local src="$1"
  local dest="$HOME/.$2"
  ln -sf "$src" "$dest"
}

for file in "${filenames[@]}"; do
  dotfile="$HOME/dotfiles/$file"
  [[ -f "$dotfile" ]] || continue
  link $dotfile $file
done

echo "Done linking dotfiles"
