#!/bin/bash

filenames=("bashrc" "vimrc" "tmux.conf" "inputrc")

for file in "${filenames[@]}"; do
  dotfile="$HOME/dotfiles/$file"
  [[ -f "$dotfile" ]] || continue
  ln -sf "$dotfile" "$HOME/.$file"
done

echo "Done linking dotfiles"
