#!/bin/bash

filenames=("bashrc" "vimrc" "tmux.conf" "inputrc")

link() {
  local src="$1"
  local dest="$HOME/.$2"
  ln -sf "$src" "$dest"
}

for file in "${filenames[@]}"; do
  dotfile="$HOME/dotfiles/$file"
  [[ -f "$dotfile" ]] || continue
  link $dotfile $file
done

if [[ -f .env ]]; then
  set -a
  source .env
  set +a
fi

if [[ -n "${OBSIDIAN:-}" ]]; then
  ln -sf "$HOME/dotfiles/obsidian.vimrc" "$OBSIDIAN/.obsidian.vimrc"
else
  echo "Skipping Obsidian vimrc: OBSIDIAN is not set"
fi

echo "Done linking dotfiles"
